name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove node_modules and cache
        run: |
          rm -rf node_modules
          rm -rf ~/.npm
      - name: Install packages
        run: rm -rf node_modules && npm ci --verbose
      - name: Start server
        run: |
          rm -rf node_modules/.cache/babel-loader
          npm run start &
          sh -c 'until curl -sSf http://localhost:3000 > /dev/null; do sleep 1; done'
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          # Records to Cypress Cloud
          record: true
          run: |
            rm -rf node_modules/.cache/babel-loader
            npx run e2e
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.BBQE_TOKEN }}
